# Generated by Django 6.1.1 on 2026-10-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('house', 'House / Apartment'), ('land', 'Land'), ('car', 'Car'), ('motorbike', 'Motorbike'), ('hotel', 'Hotel / Commercial'), ('commercial', 'Commercial'), ('service', 'Service')], db_index=True, default='house', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_message', 'New Message'), ('new_offer', 'New Offer'), ('new_conversation', 'New Conversation'), ('new_contact', 'New Contact'), ('visit_request', 'Visit Request'), ('visit_confirmed', 'Visit Confirmed'), ('visit_changed', 'Visit Changed'), ('listing_approved', 'Listing Approved'), ('listing_rejected', 'Listing Rejected'), ('payment_status', 'Payment Status'), ('document_signing', 'Document Signing'), ('follow_up', 'Follow-up Reminder'), ('system', 'System')], max_length=30),
        ),
    ]
