# Generated by Django 6.1.1 on 2026-10-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0002_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelspec',
            name='has_commercial_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='landspec',
            name='is_encumbrance_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='landspec',
            name='land_use_category',
            field=models.CharField(blank=True, choices=[('Residential', 'Residential Building Land'), ('Commercial', 'Commercial / Mixed-Use Land'), ('Agricultural', 'Agricultural / Farming Land'), ('Industrial', 'Industrial / Logistics Land'), ('Forestry', 'Forestry / Conservation'), ('WetlandBuffer', 'Wetland Buffer / Environmental Protection')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='landspec',
            name='tenure_type',
            field=models.CharField(blank=True, choices=[('EmphyteuticLease', 'Emphyteutic Lease (State 99-Year Leasehold)'), ('Freehold', 'Freehold (Ubukonde)')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='residentialspec',
            name='parking_spaces',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespec',
            name='drivetrain',
            field=models.CharField(blank=True, choices=[('4WD', '4WD / 4x4'), ('AWD', 'All-Wheel Drive'), ('FWD', 'Front-Wheel Drive'), ('RWD', 'Rear-Wheel Drive')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclespec',
            name='fuel_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclespec',
            name='has_air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehiclespec',
            name='rra_customs_status',
            field=models.CharField(blank=True, choices=[('DutyPaid', 'Customs Duty Paid'), ('InBond', 'In-Bond / Transit'), ('Exempt', 'Duty-Free Exemption')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiclespec',
            name='transmission',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
