# Generated by Django 5.1.3 on 2024-12-06 23:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0002_customermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
