# Generated by Django 5.1.3 on 2024-12-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0004_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented')], default='Available', max_length=20),
        ),
    ]
