# Generated by Django 5.1.3 on 2024-12-13 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0006_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customermessage',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='updates',
            name='created_at',
            field=models.DateField(),
        ),
    ]
