# Generated by Django 5.1.3 on 2024-12-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0007_updates_end_date_alter_customermessage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='end_date',
            field=models.DateField(),
        ),
    ]
