# Generated by Django 5.1.3 on 2024-12-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0008_alter_updates_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
