# Generated by Django 5.1.3 on 2024-12-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0009_customermessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessage',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
