# Generated by Django 5.1.3 on 2024-12-14 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0012_historicalcustomermessage_historicalemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='action',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urugwiro.lease'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urugwiro.customermessage'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urugwiro.owner'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urugwiro.property'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urugwiro.tenant'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
