# Generated by Django 5.1.3 on 2024-12-14 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0013_changelog_description_alter_changelog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urugwiro.lease'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urugwiro.customermessage'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urugwiro.owner'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urugwiro.property'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urugwiro.tenant'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
