# Generated by Django 5.1.3 on 2024-12-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0015_alter_changelog_lease_alter_changelog_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalemail',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallease',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallease',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicallease',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='historicallease',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='historicalowner',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalowner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproperty',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicaltenant',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltenant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalunit',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalunit',
            name='property',
        ),
        migrations.RemoveField(
            model_name='historicalupdates',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCustomerMessage',
        ),
        migrations.DeleteModel(
            name='HistoricalEmail',
        ),
        migrations.DeleteModel(
            name='HistoricalLease',
        ),
        migrations.DeleteModel(
            name='HistoricalOwner',
        ),
        migrations.DeleteModel(
            name='HistoricalProperty',
        ),
        migrations.DeleteModel(
            name='HistoricalTenant',
        ),
        migrations.DeleteModel(
            name='HistoricalUnit',
        ),
        migrations.DeleteModel(
            name='HistoricalUpdates',
        ),
    ]
