# Generated by Django 5.1.3 on 2024-12-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0016_remove_historicalemail_history_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeLog',
        ),
    ]
