# Generated by Django 5.1.3 on 2024-12-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0017_delete_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='contract_signed',
            field=models.BooleanField(default=False),
        ),
    ]
