# Generated by Django 5.1.3 on 2024-12-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0018_lease_contract_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='contract_archived',
            field=models.BooleanField(default=False),
        ),
    ]
