# Generated by Django 5.1.3 on 2024-12-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0020_custrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='contract_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
