# Generated by Django 5.1.3 on 2024-12-15 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0021_lease_contract_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='urugwiro.property'),
        ),
    ]
