# Generated by Django 5.1.3 on 2024-12-16 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0022_lease_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
