# Generated by Django 5.1.4 on 2024-12-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0023_property_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='contract_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
