# Generated by Django 5.1.4 on 2024-12-17 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0024_lease_contract_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='owner',
        ),
    ]
