# Generated by Django 5.1.4 on 2024-12-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0025_remove_lease_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='unit',
        ),
    ]
