# Generated by Django 5.1.4 on 2024-12-18 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0027_maintenancerequest_message_payment_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_likes', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='urugwiro.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
