# Generated by Django 6.0.2 on 2026-03-10 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0028_likedproperties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Tenant', 'Tenant'), ('Admin', 'Admin'), ('Agent', 'Agent'), ('Seller', 'Seller')], default='Tenant', max_length=10),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True, help_text='Short biography / experience summary')),
                ('specialization', models.CharField(blank=True, help_text='e.g. Residential, Commercial, Land', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='agent_images')),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_deals', models.IntegerField(default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='urugwiro.agent')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Land', 'Land'), ('Apartment', 'Apartment'), ('Commercial', 'Commercial'), ('Villa', 'Villa'), ('Warehouse', 'Warehouse')], max_length=20)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Asking price in Frw', max_digits=15)),
                ('negotiable', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(default='Kigali', max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Size in square meters', max_digits=12, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('has_title_deed', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_garden', models.BooleanField(default=False)),
                ('is_furnished', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='sale_property_images')),
                ('image_2', models.ImageField(blank=True, upload_to='sale_property_images')),
                ('image_3', models.ImageField(blank=True, upload_to='sale_property_images')),
                ('image_4', models.ImageField(blank=True, upload_to='sale_property_images')),
                ('image_5', models.ImageField(blank=True, upload_to='sale_property_images')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or video link for virtual tour')),
                ('status', models.CharField(choices=[('listed', 'Listed'), ('under_negotiation', 'Under Negotiation'), ('sold', 'Sold'), ('withdrawn', 'Withdrawn')], default='listed', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('date_listed', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_properties', to='urugwiro.agent')),
            ],
            options={
                'verbose_name_plural': 'Sale Properties',
                'ordering': ['-date_listed'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='urugwiro.saleproperty')),
            ],
            options={
                'verbose_name_plural': 'Property Inquiries',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('counter_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('message', models.TextField(blank=True, help_text='Message to seller/agent')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('countered', 'Countered'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_handled', to='urugwiro.agent')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to=settings.AUTH_USER_MODEL)),
                ('sale_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='urugwiro.saleproperty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='urugwiro.agent')),
                ('sale_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to='urugwiro.saleproperty')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('id_number', models.CharField(blank=True, help_text='National ID or passport', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='seller_images')),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='saleproperty',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_properties', to='urugwiro.seller'),
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Agent notes from the visit')),
                ('report', models.TextField(blank=True, help_text='Detailed inspection report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='urugwiro.agent')),
                ('sale_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='urugwiro.saleproperty')),
                ('visitor', models.ForeignKey(blank=True, help_text='Buyer who requested the visit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
