# Generated by Django 6.1.1 on 2026-09-18 09:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0034_propertyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('listing_type', models.CharField(choices=[('rental', 'Rental'), ('sale', 'Sale'), ('land', 'Land'), ('vehicle', 'Vehicle'), ('service', 'Service')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='RWF', max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(default='Kigali', max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('listed', 'Listed'), ('under_negotiation', 'Under Negotiation'), ('sold', 'Sold'), ('rented', 'Rented'), ('withdrawn', 'Withdrawn')], default='listed', max_length=20)),
                ('verification_level', models.CharField(choices=[('none', 'Not Verified'), ('submitted', 'Documents Submitted'), ('verified', 'Urugwiro Verified'), ('professional', 'Professionally Inspected')], default='none', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('date_listed', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['-date_listed'],
            },
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propertyinquiry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='saleproperty',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sitevisit',
            options={},
        ),
        migrations.RemoveField(
            model_name='custrequest',
            name='property',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='property',
        ),
        migrations.RemoveField(
            model_name='likedproperties',
            name='property',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='property',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='property',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='property',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='property',
        ),
        migrations.AlterField(
            model_name='agent',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='email',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='recipient_email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender_email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='saleproperty',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='saleproperty',
            name='size_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='saleproperty',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='report',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Agent', 'Agent'), ('Admin', 'Admin')], default='Buyer', max_length=10),
        ),
        migrations.CreateModel(
            name='LandExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Agricultural', 'Agricultural')], max_length=50)),
                ('plot_size', models.DecimalField(decimal_places=2, max_digits=12)),
                ('size_unit', models.CharField(default='sqm', max_length=20)),
                ('terrain', models.CharField(blank=True, max_length=100)),
                ('road_access', models.BooleanField(default=False)),
                ('utilities', models.TextField(blank=True, help_text='Electricity, Water, etc.')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land_data', to='urugwiro.listing')),
            ],
        ),
        migrations.AddField(
            model_name='custrequest',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cust_requests', to='urugwiro.listing'),
        ),
        migrations.AddField(
            model_name='lease',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='urugwiro.listing'),
        ),
        migrations.AddField(
            model_name='likedproperties',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='urugwiro.listing'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maint_requests', to='urugwiro.listing'),
        ),
        migrations.AddField(
            model_name='payment',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='urugwiro.listing'),
        ),
        migrations.AddField(
            model_name='unit',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='urugwiro.listing'),
        ),
        migrations.AddField(
            model_name='visit',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='urugwiro.listing'),
        ),
        migrations.CreateModel(
            name='ListingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='listing_media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('360', '360 Tour')], default='image', max_length=20)),
                ('category', models.CharField(blank=True, help_text='e.g. Interior, Exterior, Drone', max_length=50)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='urugwiro.listing')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='owner_profiles')),
                ('is_verified', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing_owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='urugwiro.listingowner'),
        ),
        migrations.CreateModel(
            name='RentalExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Commercial', 'Commercial')], max_length=50)),
                ('number_of_units', models.IntegerField(default=1)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_data', to='urugwiro.listing')),
            ],
        ),
        migrations.CreateModel(
            name='SaleExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negotiable', models.BooleanField(default=True)),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('has_title_deed', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_garden', models.BooleanField(default=False)),
                ('is_furnished', models.BooleanField(default=False)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_data', to='urugwiro.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField(default=0)),
                ('certifications', models.TextField(blank=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_data', to='urugwiro.listing')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Motorcycle', 'Motorcycle')], max_length=20)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('engine_capacity', models.CharField(blank=True, max_length=50)),
                ('condition', models.CharField(max_length=100)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_data', to='urugwiro.listing')),
            ],
        ),
    ]
