# Generated by Django 6.1.1 on 2026-09-18 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0035_listing_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custrequest',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urugwiro.property'),
        ),
        migrations.AddField(
            model_name='lease',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urugwiro.property'),
        ),
        migrations.AddField(
            model_name='likedproperties',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urugwiro.property'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urugwiro.property'),
        ),
        migrations.AddField(
            model_name='payment',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urugwiro.property'),
        ),
        migrations.AddField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urugwiro.property'),
        ),
        migrations.AddField(
            model_name='visit',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urugwiro.property'),
        ),
    ]
