# Generated by Django 6.1.1 on 2026-09-18 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0036_custrequest_property_lease_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentassignment',
            name='sale_property',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='sale_property',
        ),
        migrations.RemoveField(
            model_name='propertyinquiry',
            name='sale_property',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='sale_property',
        ),
        migrations.AddField(
            model_name='agentassignment',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to='urugwiro.listing'),
        ),
        migrations.AddField(
            model_name='offer',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='urugwiro.listing'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='urugwiro.listing'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='urugwiro.listing'),
        ),
    ]
