# Generated by Django 6.1.1 on 2026-09-18 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0037_remove_agentassignment_sale_property_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Material icon name', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Agent', 'Agent'), ('Admin', 'Admin'), ('RentalManager', 'Rental Manager')], default='Buyer', max_length=20),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='articles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='urugwiro.articlecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('LAND', 'Land'), ('BUILDING', 'Building'), ('UNIT', 'Unit'), ('VEHICLE', 'Vehicle'), ('SERVICE', 'Service')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('boundary_geojson', models.TextField(blank=True, help_text='GeoJSON polygon for land assets', null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('cell', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='urugwiro.asset')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='urugwiro.asset'),
        ),
        migrations.CreateModel(
            name='CommercialSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoning_type', models.CharField(blank=True, choices=[('Retail', 'Retail'), ('Office', 'Office'), ('Industrial', 'Industrial'), ('Mixed', 'Mixed')], max_length=50, null=True)),
                ('power_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='KVA', max_digits=10, null=True)),
                ('loading_bays', models.IntegerField(default=0)),
                ('parking_spaces', models.IntegerField(default=0)),
                ('foot_traffic_score', models.IntegerField(default=0, help_text='1-10')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_spec', to='urugwiro.asset')),
            ],
        ),
        migrations.CreateModel(
            name='HotelSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('total_rooms', models.IntegerField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, default=dict, help_text="e.g. {'pool': true, 'gym': true}")),
                ('occupancy_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('management_type', models.CharField(blank=True, choices=[('Owner-Managed', 'Owner-Managed'), ('Franchise', 'Franchise'), ('Corporate', 'Corporate')], max_length=50, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_spec', to='urugwiro.asset')),
            ],
        ),
        migrations.CreateModel(
            name='LandSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terrain', models.CharField(blank=True, choices=[('Flat', 'Flat'), ('Sloped', 'Sloped'), ('Hilly', 'Hilly'), ('Rocky', 'Rocky')], max_length=50, null=True)),
                ('road_access', models.BooleanField(default=False)),
                ('soil_type', models.CharField(blank=True, max_length=100, null=True)),
                ('topography', models.TextField(blank=True, null=True)),
                ('title_deed_number', models.CharField(blank=True, help_text='UPT Number', max_length=100, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land_spec', to='urugwiro.asset')),
            ],
        ),
        migrations.CreateModel(
            name='ListingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_audits', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='urugwiro.listing')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ResidentialSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('kitchen_type', models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('American', 'American')], max_length=50, null=True)),
                ('balcony', models.BooleanField(default=False)),
                ('is_furnished', models.BooleanField(default=False)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residential_spec', to='urugwiro.asset')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('engine_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_spec', to='urugwiro.asset')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='verification_docs/')),
                ('document_type', models.CharField(help_text='e.g. Title Deed, Registration, ID', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_docs', to='urugwiro.listing')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='rejected', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='urugwiro.verificationdocument')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
