# Generated by Django 6.1.1 on 2026-09-21 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0039_systemsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='district',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sector',
        ),
        migrations.AddField(
            model_name='commercialspec',
            name='has_backup_generator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commercialspec',
            name='total_floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelspec',
            name='conference_halls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotelspec',
            name='has_commercial_license',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelspec',
            name='has_restaurant_bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landspec',
            name='cadastral_sketch',
            field=models.ImageField(blank=True, null=True, upload_to='cadastral_sketches/'),
        ),
        migrations.AddField(
            model_name='landspec',
            name='drainage_system',
            field=models.CharField(blank=True, help_text='Covered, Open, Natural', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landspec',
            name='electricity_onsite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landspec',
            name='is_in_wetland_buffer_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landspec',
            name='power_pole_distance_meters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landspec',
            name='road_type',
            field=models.CharField(blank=True, help_text='Asphalt/Tarmac, Cobblestone, Murram/Dirt, Footpath', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landspec',
            name='upi_number',
            field=models.CharField(blank=True, help_text='Unique Parcel Identifier (UPI) e.g. 1/03/05/02/1234', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landspec',
            name='water_line_distance_meters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landspec',
            name='water_onsite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landspec',
            name='zoning_code',
            field=models.CharField(blank=True, help_text='e.g. R1, R2, R3, C1, Commercial, Industrial, Agricultural', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('house', 'House / Apartment'), ('land', 'Land'), ('car', 'Car'), ('motorbike', 'Motorbike'), ('hotel', 'Hotel / Commercial'), ('service', 'Service')], db_index=True, default='house', max_length=30),
        ),
        migrations.AddField(
            model_name='listing',
            name='purpose',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], db_index=True, default='sale', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='rental_frequency',
            field=models.CharField(blank=True, choices=[('per_day', 'Per Day'), ('per_month', 'Per Month'), ('per_year', 'Per Year')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='listingmedia',
            name='hotspots',
            field=models.JSONField(blank=True, default=list, help_text='Navigation pins linking to other rooms'),
        ),
        migrations.AddField(
            model_name='listingmedia',
            name='initial_pitch',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='listingmedia',
            name='initial_yaw',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='listingmedia',
            name='room_name',
            field=models.CharField(blank=True, help_text='e.g. Living Room, Master Bedroom, Compound', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='urugwiro.listing'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='RWF', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'MTN Mobile Money'), ('airtel', 'Airtel Money'), ('card', 'Credit / Debit Card'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], default='momo', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('rent', 'Rent Payment'), ('deposit', 'Security Deposit / Escrow'), ('purchase', 'Asset Purchase'), ('booking', 'Site Visit / Inspection Fee')], default='rent', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='built_up_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='compound_size_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='electricity_meter',
            field=models.CharField(blank=True, help_text='e.g. Cash Power Dedicated, Shared', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='has_backup_generator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='has_elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='has_garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='has_solar_water_heater',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='has_staff_quarters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='has_swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='has_water_tank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='monthly_service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='road_access_type',
            field=models.CharField(blank=True, help_text='e.g. Tarmac, Cobblestone, Murram, Pedestrian', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='security_type',
            field=models.CharField(blank=True, help_text='e.g. Gated, Electric Fence, Perimeter Wall', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='sub_type',
            field=models.CharField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment'), ('SingleFamily', 'Single Family House'), ('Townhouse', 'Townhouse'), ('ModestHouse', 'Modest / Small House'), ('Duplex', 'Duplex'), ('Studio', 'Studio')], default='SingleFamily', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='body_type',
            field=models.CharField(blank=True, help_text='SUV, Sedan, Pickup, Minibus, Sportbike, Cruiser', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='condition',
            field=models.CharField(blank=True, help_text='Brand New, Used Foreign, Used Local', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='controle_technique_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='has_delivery_rack',
            field=models.BooleanField(default=False, help_text='For delivery motorbikes'),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='includes_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='includes_helmet',
            field=models.BooleanField(default=False, help_text='For motorbikes'),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='plate_type',
            field=models.CharField(blank=True, help_text='Private (RAx), Commercial Yellow Plate, Temporary', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='seating_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Motorcycle', 'Motorcycle')], default='Car', max_length=20),
        ),
        migrations.AlterField(
            model_name='landspec',
            name='terrain',
            field=models.CharField(blank=True, choices=[('Flat', 'Flat'), ('Gentle Slope', 'Gentle Slope'), ('Sloped', 'Sloped'), ('Hilly', 'Hilly'), ('Rocky', 'Rocky'), ('Valley', 'Valley')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='landspec',
            name='title_deed_number',
            field=models.CharField(blank=True, help_text='UPI / Title Deed Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listingmedia',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Interior, Exterior, Drone, FloorPlan', max_length=50),
        ),
        migrations.AlterField(
            model_name='listingmedia',
            name='file',
            field=models.FileField(upload_to='listing_media/'),
        ),
        migrations.AlterField(
            model_name='listingmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('360', '360 Tour'), ('model_3d', '3D Digital Twin (.glb)'), ('cadastral_sketch', 'UPI Cadastral Sketch')], default='image', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='urugwiro.tenant'),
        ),
        migrations.AlterField(
            model_name='vehiclespec',
            name='engine_capacity',
            field=models.CharField(blank=True, help_text='e.g. 2000cc or 150cc', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespec',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclespec',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiclespec',
            name='transmission',
            field=models.CharField(default='Automatic', max_length=50),
        ),
    ]
