# Generated by Django 6.1.1 on 2026-09-21 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0040_remove_listing_city_remove_listing_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='escrow_proposed_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='offer',
            name='financing_type',
            field=models.CharField(choices=[('cash', 'Cash / Direct Escrow'), ('bank_mortgage', 'Bank Mortgage / Financing'), ('installment', 'Staged Installments')], default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='proposed_closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TransactionDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deal_type', models.CharField(choices=[('sale', 'Property Sale Conveyance'), ('rental', 'Rental Lease Agreement')], default='sale', max_length=20)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='RWF', max_length=10)),
                ('escrow_deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('escrow_status', models.CharField(choices=[('pending_deposit', 'Awaiting Escrow Deposit'), ('held_in_escrow', 'Held in Bank Escrow'), ('released_to_seller', 'Disbursed to Seller'), ('refunded', 'Refunded to Buyer')], default='pending_deposit', max_length=30)),
                ('current_stage', models.CharField(default='offer_accepted', max_length=40)),
                ('progress_percentage', models.IntegerField(default=15)),
                ('irembo_bill_id', models.CharField(blank=True, help_text='Irembo Gov Notary Application ID', max_length=100)),
                ('land_upi', models.CharField(blank=True, help_text='Rwandan Parcel UPI Number', max_length=50)),
                ('notary_office', models.CharField(blank=True, help_text='e.g. Gasabo District Notary Office', max_length=150)),
                ('target_closing_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals_managed', to='urugwiro.agent')),
                ('buyer_or_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='urugwiro.listing')),
                ('offer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal', to='urugwiro.offer')),
                ('seller_or_landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_as_seller', to='urugwiro.listingowner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('title_deed', 'Official Title Deed / UPI Certificate'), ('sales_contract', 'Bilateral Sales Agreement'), ('lease_contract', 'Residential / Commercial Lease Agreement'), ('escrow_receipt', 'Bank Escrow Deposit Confirmation'), ('irembo_receipt', 'Irembo Notary Application Bill / Receipt'), ('inspection_report', 'État des Lieux / Technical Inspection'), ('tax_clearance', 'RRA Property Tax Clearance Certificate'), ('id_proof', 'National ID / Passport Verification'), ('vehicle_carte_jaune', 'Vehicle Logbook (Carte Jaune)'), ('controle_technique', 'Police Vehicle Inspection Certificate')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='deal_paperwork/%Y/%m/')),
                ('is_verified', models.BooleanField(default=False)),
                ('ai_extracted_data', models.JSONField(blank=True, default=dict)),
                ('ai_validation_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_deal_docs', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='urugwiro.transactiondeal')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
