# Generated by Django 6.1.1 on 2026-09-21 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0041_offer_escrow_proposed_percent_offer_financing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Agent', 'Agent'), ('Admin', 'Admin'), ('RentalManager', 'Rental Manager'), ('Tenant', 'Tenant'), ('Owner', 'Owner')], default='Buyer', max_length=20),
        ),
        migrations.CreateModel(
            name='ListingProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=150)),
                ('id_number', models.CharField(blank=True, help_text='National ID or Passport Number', max_length=50)),
                ('owner_relationship', models.CharField(choices=[('direct_owner', 'Direct Property Owner'), ('representative', 'Authorized Representative (POA)'), ('broker', 'Licensed Broker / Agency'), ('developer', 'Real Estate Developer')], default='direct_owner', max_length=30)),
                ('title', models.CharField(help_text='e.g. Modern 4BR Villa in Nyarutarama', max_length=200)),
                ('asset_type', models.CharField(choices=[('house', 'Residential Villa / House'), ('land', 'Land Parcel'), ('apartment', 'Apartment / Condominium'), ('commercial', 'Commercial / Office Building'), ('vehicle', 'Mobility / Vehicle')], default='house', max_length=30)),
                ('purpose', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent / Lease')], default='sale', max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('cell', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('land_upi', models.CharField(blank=True, help_text='Rwandan Land UPI Number', max_length=50)),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='RWF', max_length=10)),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('preferred_visit_date', models.DateField(blank=True, null=True)),
                ('preferred_time_slot', models.CharField(choices=[('morning', 'Morning (09:00 - 12:00)'), ('afternoon', 'Afternoon (14:00 - 17:00)'), ('anytime', 'Anytime during working hours')], default='morning', max_length=20)),
                ('site_contact_name', models.CharField(blank=True, max_length=150)),
                ('site_contact_phone', models.CharField(blank=True, max_length=30)),
                ('site_access_notes', models.TextField(blank=True, help_text='Gate codes, landmarks, caretaker details')),
                ('status', models.CharField(choices=[('pending', 'Pending Cadastral Review'), ('visit_scheduled', 'Physical Visit Scheduled'), ('inspected', 'Inspected & Surveyed'), ('approved', 'Approved & Converted to Listing'), ('rejected', 'Rejected / Ineligible')], default='pending', max_length=30)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_proposals', to='urugwiro.agent')),
                ('converted_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_proposal', to='urugwiro.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
