# Generated by Django 6.1.1 on 2026-09-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0042_alter_user_role_listingproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingproposal',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic domain-specific specs (vehicle, land, commercial, residential)'),
        ),
        migrations.AddField(
            model_name='listingproposal',
            name='sub_type',
            field=models.CharField(blank=True, help_text='e.g. Villa, Apartment, Plot, Office, SUV', max_length=50),
        ),
    ]
