# Generated by Django 6.1.1 on 2026-09-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0043_listingproposal_specifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landspec',
            name='building_coverage_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max BCR percentage e.g. 50%', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='landspec',
            name='floor_area_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='FAR index', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='landspec',
            name='has_fiber_conduit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landspec',
            name='is_encumbrance_free',
            field=models.BooleanField(default=True, help_text='Free of bank mortgages, caveats, or court disputes'),
        ),
        migrations.AddField(
            model_name='landspec',
            name='land_use_category',
            field=models.CharField(choices=[('Residential', 'Residential Building Land'), ('Commercial', 'Commercial / Mixed-Use Land'), ('Agricultural', 'Agricultural / Farming Land'), ('Industrial', 'Industrial / Logistics Land'), ('Forestry', 'Forestry / Conservation'), ('WetlandBuffer', 'Wetland Buffer / Environmental Protection')], default='Residential', max_length=50),
        ),
        migrations.AddField(
            model_name='landspec',
            name='lease_years_remaining',
            field=models.IntegerField(blank=True, help_text='Years remaining on state leasehold (e.g. 85)', null=True),
        ),
        migrations.AddField(
            model_name='landspec',
            name='max_permitted_floors',
            field=models.CharField(blank=True, help_text='e.g. G+1, G+2, G+4 under Master Plan', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landspec',
            name='slope_gradient_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gradient slope percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='landspec',
            name='tenure_type',
            field=models.CharField(choices=[('EmphyteuticLease', 'Emphyteutic Lease (State 99-Year Leasehold)'), ('Freehold', 'Freehold (Ubukonde)')], default='EmphyteuticLease', max_length=50),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='backup_generator_kva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Generator capacity in KVA', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='has_cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='has_fiber_internet',
            field=models.BooleanField(default=False, help_text='Optical fiber internet installed'),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='has_three_phase_power',
            field=models.BooleanField(default=False, help_text='3-Phase electricity connection'),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='master_plan_zoning',
            field=models.CharField(blank=True, help_text='e.g. R1, R1A, R2, R3', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='parking_spaces',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='water_tank_capacity_liters',
            field=models.IntegerField(blank=True, help_text='Reserve water capacity e.g. 5000L', null=True),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='drivetrain',
            field=models.CharField(choices=[('4WD', '4WD / 4x4'), ('AWD', 'All-Wheel Drive (AWD)'), ('FWD', 'Front-Wheel Drive (FWD)'), ('RWD', 'Rear-Wheel Drive (RWD)')], default='FWD', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='has_air_conditioning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='has_leather_seats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='has_reverse_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='has_service_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='has_sunroof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='horsepower',
            field=models.IntegerField(blank=True, help_text='Engine Horsepower (HP)', null=True),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='plate_number',
            field=models.CharField(blank=True, help_text='e.g. RAC 456 D or IT Yellow Plate', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='rra_customs_status',
            field=models.CharField(choices=[('DutyPaid', 'RRA Customs Duty Paid (Rwanda Cleared)'), ('InBond', 'In-Bond / Transit (Customs Duty Unpaid)'), ('Exempt', 'Diplomatic / NGO Duty-Free Exemption')], default='DutyPaid', max_length=30),
        ),
        migrations.AddField(
            model_name='vehiclespec',
            name='vin_chassis_number',
            field=models.CharField(blank=True, help_text='Chassis / VIN number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='landspec',
            name='zoning_code',
            field=models.CharField(blank=True, help_text='e.g. R1, R1A, R2, R3, C1, C2, A1, Industrial, Agricultural', max_length=50, null=True),
        ),
    ]
