# Generated by Django 6.1.1 on 2026-09-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0044_landspec_building_coverage_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listed_by_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('agent', 'Agent')], default='seller', help_text='Which dashboard role created this listing', max_length=20),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='apartment_floor_plan',
            field=models.JSONField(blank=True, help_text="JSON: floor-by-floor breakdown [{floor: 1, units: [{unit: '101', beds: 2, baths: 1, sqm: 80, view: 'Garden', price: 500000, status: 'available'}]}]", null=True),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='apartment_selling_mode',
            field=models.CharField(blank=True, choices=[('whole_building', 'Entire Building'), ('per_floor', 'Per Floor'), ('per_unit', 'Per Unit / Room')], help_text='How the apartment is being sold/rented: entire building, per floor, or per unit', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='balcony_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='parking_slot_number',
            field=models.CharField(blank=True, help_text='e.g. B1-14, P2-07', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='total_building_floors',
            field=models.IntegerField(blank=True, help_text='Total floors in the apartment building', null=True),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='unit_number',
            field=models.CharField(blank=True, help_text='e.g. Suite 302, Unit A4', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='residentialspec',
            name='unit_orientation',
            field=models.CharField(blank=True, help_text='e.g. North-East Skyline, Golf Course View, Courtyard', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='residentialspec',
            name='sub_type',
            field=models.CharField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment'), ('SingleFamily', 'Single Family House'), ('Townhouse', 'Townhouse'), ('ModestHouse', 'Modest / Small House'), ('Duplex', 'Duplex'), ('Studio', 'Studio'), ('Penthouse', 'Penthouse')], default='SingleFamily', max_length=50),
        ),
    ]
