# Generated by Django 6.1.1 on 2026-09-22 18:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0045_listing_listed_by_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(choices=[('property_sale', 'Bilateral Property Sale Agreement (Compromis de Vente)'), ('apartment_unit_sale', 'Condominium Unit Purchase Agreement'), ('land_sale', 'Bilateral Land Conveyance Agreement'), ('residential_lease', 'Residential Tenancy Agreement'), ('commercial_lease', 'Commercial Lease Agreement'), ('vehicle_sale', 'Motor Vehicle Bill of Sale'), ('spousal_consent', 'Spousal Consent Affidavit'), ('handover_protocol', 'Inspection & Key Handover Protocol')], default='property_sale', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('contract_html_content', models.TextField(blank=True)),
                ('contract_pdf', models.FileField(blank=True, null=True, upload_to='signed_contracts/%Y/%m/')),
                ('sha256_hash', models.CharField(blank=True, help_text='Cryptographic document fingerprint', max_length=64)),
                ('qr_verification_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Drafting & Review'), ('pending_signatures', 'Awaiting Signatures'), ('partially_signed', 'Partially Signed'), ('fully_executed', 'Fully Executed & Sealed'), ('voided', 'Voided / Expired')], default='draft', max_length=30)),
                ('signers_manifest', models.JSONField(blank=True, default=list)),
                ('requires_spousal_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='urugwiro.transactiondeal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
