# Generated by Django 6.1.1 on 2026-09-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urugwiro', '0046_contractagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinquiry',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propertyinquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
